s|http://bokeh.pydata.org/en/latest/|https://docs.bokeh.org/en/latest/|g
s|http://creativecommons.org/licenses/by-nc-sa/4.0/legalcode|https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode|g
s|http://dmlc.ml/rstats/2016/03/10/xgboost.html|https://dmlc.ml/|g
s|http://ess.r-project.org/|https://ess.r-project.org/|g
s|http://ess.r-project.org/refcard.pdf|https://ess.r-project.org/refcard.pdf|g
s|http://f.briatte.org/r/submitting-packages-to-cran|https://f.briatte.org/r/submitting-packages-to-cran|g
s|http://github.com/jennybc/gapminder|https://github.com/jennybc/gapminder|g
s|http://icon.colorado.edu|https://icon.colorado.edu/|g
s|http://imagemagick.org/|https://imagemagick.org/|g
s|http://juliasilge.com/blog/How-I-Stopped/|https://juliasilge.com/blog/how-i-stopped/|g
s|http://md.ekstrandom.net/blog/2016/04/using-r/|https://md.ekstrandom.net/blog/2016/04/using-r|g
s|http://r4ds.had.co.nz/|https://r4ds.had.co.nz/|g
s|http://r4stats.com/books/free-version/|https://r4stats.com/books/free-version/|g
s|http://rpy.sourceforge.net/|https://sourceforge.net/projects/rpy/|g
s|http://rstudio.github.io/DT/|https://rstudio.github.io/DT/|g
s|http://rsuite.io|http://rsuite.io/|g
s|http://rtalk.org|https://rtalk.org/|g
s|http://shop.oreilly.com/product/0636920063704.do|https://www.oreilly.com/library/view/r-graphics-cookbook/9781491978597/|g
s|http://shop.oreilly.com/product/0636920174851.do|https://www.oreilly.com/library/view/r-cookbook-2nd/9781492040675/|g
s|http://shop.oreilly.com/product/9781593273842.do|https://www.oreilly.com/library/view/the-art-of/9781593273842/|g
s|http://sigmajs.org/|https://www.sigmajs.org/|g
s|http://spark.rstudio.com/|https://spark.posit.co/|g
s|http://spotfire.tibco.com/discover-spotfire/what-does-spotfire-do/predictive-analytics/tibco-enterprise-runtime-for-r-terr|https://www.spotfire.com/|g
s|http://stat.ethz.ch/R-manual/R-devel/library/compiler/html/compile.html|https://stat.ethz.ch/R-manual/R-devel/library/compiler/html/compile.html|g
s|http://statnet.org/|https://statnet.org/|g
s|http://tidytextmining.com/index.html|https://www.tidytextmining.com/index.html|g
s|http://toddwschneider.com/posts/ballr-interactive-nba-shot-charts-with-r-and-shiny/|https://toddwschneider.com/posts/ballr-interactive-nba-shot-charts-with-r-and-shiny/|g
s|http://trestletech.com/2016/03/09/eigencoder/|https://trestletech.com/2016/03/09/eigencoder/|g
s|http://tryr.codeschool.com/|https://www.pluralsight.com/codeschool|g
s|http://www.bio7.org/|https://bio7.org/|g
s|http://www.burns-stat.com/pages/Tutor/R_inferno.pdf|https://www.burns-stat.com/pages/Tutor/R_inferno.pdf|g
s|http://www.deducer.org/pmwiki/pmwiki.php?n=Main.DeducerManual?from=Main.HomePage|https://www.deducer.org/pmwiki.php?n=Main.DeducerManual?from=Main.HomePage|g
s|http://www.example.com|http://www.example.com/|g
s|http://www.manning.com/kabacoff2/|https://www.manning.com/books/r-in-action-second-edition|g
s|http://www.r-bloggers.com/|https://www.r-bloggers.com/|g
s|http://www.r-statistics.com/2016/03/its-not-the-p-values-fault-reflections-on-the-recent-asa-statement/|https://www.r-statistics.com/2016/03/its-not-the-p-values-fault-reflections-on-the-recent-asa-statement/|g
s|http://www.renjin.org/|https://www.renjin.org/|g
s|http://www.springer.com/series/6991?detailsPage=titles|https://link.springer.com/series/6991/books?error=cookies_not_supported&code=58ac743d-15bc-4529-83d0-0710cc3c3148|g
s|http://www1.cuni.cz/~obo/r_surprises.html|https://www1.cuni.cz/~obo/r_surprises.html|g
s|https://bookdown.org/|https://bookdown.org/home/|g
s|https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg|https://cdn.jsdelivr.net/gh/sindresorhus/awesome@d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg|g
s|https://code.google.com/p/rpostgresql/|https://code.google.com/archive/p/rpostgresql|g
s|https://codecov.io/|https://about.codecov.io/|g
s|https://cran.r-project.org/package=batchtools|https://cran.r-project.org/web/packages/batchtools/index.html|g
s|https://ggplot2-exts.github.io/ggiraph.html|http://exts.ggplot2.tidyverse.org/ggiraph.html|g
s|https://github.com/GuangchuangYu/ggtree|https://github.com/YuLab-SMU/ggtree|g
s|https://github.com/Non-Contradiction/JuliaCall|https://github.com/JuliaInterop/JuliaCall|g
s|https://github.com/RomanTsegelskyi/rbooks|https://github.com/romantseg/rbooks|g
s|https://github.com/daattali/ezknitr|https://github.com/ropensci/ezknitr|g
s|https://github.com/daattali/rstudio-addins|https://github.com/daattali/addinslist|g
s|https://github.com/dgrtwo/gganimate|https://github.com/thomasp85/gganimate|g
s|https://github.com/edzer/gstat|https://github.com/r-spatial/gstat|g
s|https://github.com/facebookincubator/prophet|https://github.com/facebook/prophet|g
s|https://github.com/hadley/haven|https://github.com/tidyverse/haven|g
s|https://github.com/hadley/purrr|https://github.com/tidyverse/purrr|g
s|https://github.com/hadley/staticdocs|https://github.com/r-lib/pkgdown|g
s|https://github.com/hadley/tidyr|https://github.com/tidyverse/tidyr|g
s|https://github.com/hadley/tidyverse|https://github.com/tidyverse/tidyverse|g
s|https://github.com/jbrownlee/CleverAlgorithmsMachineLearning|https://github.com/Jason2Brownlee/CleverAlgorithmsMachineLearning|g
s|https://github.com/jennybc/reprex|https://github.com/tidyverse/reprex|g
s|https://github.com/jeroenooms/V8|https://github.com/jeroen/V8|g
s|https://github.com/jeroenooms/jsonlite|https://github.com/jeroen/jsonlite|g
s|https://github.com/jeroenooms/mongolite|https://github.com/jeroen/mongolite|g
s|https://github.com/jimhester/covr|https://github.com/r-lib/covr|g
s|https://github.com/jimhester/lintr|https://github.com/r-lib/lintr|g
s|https://github.com/johnmyleswhite/log4r|https://github.com/r-lib/log4r|g
s|https://github.com/kbenoit/quanteda|https://github.com/quanteda/quanteda|g
s|https://github.com/leeper/rio|https://github.com/gesistsa/rio|g
s|https://github.com/mablab/rpostgis|https://github.com/Cidree/rpostgis|g
s|https://github.com/masalmon/monkeylearn|https://github.com/ropensci-archive/monkeylearn|g
s|https://github.com/metrumresearchgroup/sinew|https://github.com/yonicd/sinew|g
s|https://github.com/mongosoup/rmongodb|https://github.com/dselivanov/rmongodb|g
s|https://github.com/patperry/r-utf8|https://github.com/krlmlr/utf8|g
s|https://github.com/r-lib/vroom|https://github.com/tidyverse/vroom|g
s|https://github.com/ropensci/PackageDevelopment|https://github.com/ropensci-archive/PackageDevelopment|g
s|https://github.com/ropensci/opendata|https://github.com/ropensci-archive/opendata|g
s|https://github.com/ropensci/webservices|https://github.com/cran-task-views/WebTechnologies|g
s|https://github.com/rstats-db/DBI|https://github.com/r-dbi/DBI|g
s|https://github.com/rstats-db/RMariaDB|https://github.com/r-dbi/RMariaDB|g
s|https://github.com/rstudio/d3heatmap|https://github.com/talgalili/d3heatmap|g
s|https://github.com/smbache/import/|https://github.com/rticulate/import|g
s|https://github.com/traversc/qs|https://github.com/qsbase/qs|g
s|https://github.com/trestletech/plumber|https://github.com/rstudio/plumber|g
s|https://github.com/viking/r-yaml|https://github.com/vubiostat/r-yaml|g
s|https://github.com/yihui/tinytex|https://github.com/rstudio/tinytex|g
s|https://marketplace.visualstudio.com/items?itemName=Ikuyadeu.r|https://marketplace.visualstudio.com/items?itemName=REditorSupport.r|g
s|https://plot.ly|https://plotly.com/|g
s|https://radiant-rstats.github.io/docs|https://radiant-rstats.github.io/docs/|g
s|https://rnotebook.io/|https://raspberryketone.eu.com/|g
s|https://ropensci.org|https://ropensci.org/|g
s|https://rweekly.org|https://rweekly.org/|g
s|https://sites.google.com/a/ddahl.org/rinruby-users/|https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fsites.google.com%2Fa%2Fddahl.org%2Frinruby-users%2F&followup=https%3A%2F%2Fsites.google.com%2Fa%2Fddahl.org%2Frinruby-users%2F&ifkv=AdBytiN0K3OfhjtvaHU3xZZ5_0WwikUOwMbyO_AvzaAga0aGPSYfn8lO0IhYmVvWHKM0U9Q3xkTz&osid=1&passive=1209600&flowName=WebLiteSignIn&flowEntry=ServiceLogin&dsh=S923642798%3A1754531620155943|g
s|https://twitter.com/bearloga|https://x.com/bearloga|g
s|https://twitter.com/emhrt_|https://x.com/emhrt_|g
s|https://twitter.com/hrbrmstr|https://x.com/hrbrmstr|g
s|https://twitter.com/hspter|https://x.com/hspter|g
s|https://twitter.com/jasdumas|https://x.com/jasdumas|g
s|https://twitter.com/jayjacobs|https://x.com/jayjacobs|g
s|https://twitter.com/quominus|https://x.com/quominus|g
s|https://twitter.com/rdpeng|https://x.com/rdpeng|g
s|https://www.coursera.org/specialization/jhudatascience/1|https://www.coursera.org/specializations/jhu-data-science|g
s|https://www.rstudio.com/resources/cheatsheets/|https://posit.co/resources/cheatsheets/|g
s|https://www.statistik.lmu.de/~leisch/Sweave/|https://www.stat.lmu.de/en/|g
s|https://yihui.name/tinytex/|https://yihui.org/tinytex/|g
